const ICONS = {
  tab1: require("./tab1.png"),
  tab2: require("./tab2.png"),
  tab3: require("./tab3.png"),
  tab4: require("./tab4.png"),
  tab5: require("./tab5.png"),
  tab6: require("./tab6.png"),
  register1: require("./register1.png"),
  register2: require("./register2.png"),
  register3: require("./register3.png"),
  register4: require("./register4.png"),
  register5: require("./register5.png"),
  menuIcon: require("../icons/menu-icon.png"),
  backIcon: require("../icons/backIcon.png"),
  logoutIcon: require("../icons/logoutIcon.png"),
  notificationIcon: require("../icons/notificationIcon.png"),
  galleryIcon: require("../icons/galleryIcon.png"),
  cameraIcon: require("../icons/cameraIcon.png"),
  locationPicker: require("../icons/locationPicker.png"),
  editIcon: require("../icons/editIcon.png"),
  editIcon2: require("../icons/editIcon2.png"),
  deleteIcon: require("../icons/deleteIcon.png"),
  idCardIcon: require("../icons/idCardIcon.png"),
  plotCoordinateIcon: require("../icons/plotCoordinateIcon.png"),
  clipboardIcon: require("../icons/clipboardIcon.png"),
  cellPhoneIcon: require("../icons/cellPhoneIcon.png"),
  calendarIcon: require("../icons/calendarIcon.png"),
  cameraIcon2: require("../icons/cameraIcon2.png"),
  cameraIcon3: require("../icons/cameraIcon3.png"),
  searchIcon: require("../icons/searchIcon.png"),
  phoneBookIcon: require("../icons/phoneBookIcon.png"),
  locationIcon: require("../icons/locationIcon.png"),
  optionsIcon: require("../icons/optionsIcon.png"),
  dobIcon: require("../icons/dobIcon.png"),
};

export { ICONS };
