const ADD_TODO = "ADD_TODO";
const REMOVE_TODO = "REMOVE_TODO";
const UPDATE_TODO = "UPDATE_TODO";
const CLEAR_ALL_TODOS = "CLEAR_ALL_TODOS";

const SET_USER_DATA = "SET_USER_DATA";
const SET_USER_REGION = "SET_USER_REGION";
const SET_USER_REGIONS_LIST = "SET_USER_REGIONS_LIST";
const CLEAR_USER_DATA = "CLEAR_USER_DATA";

// FARMER REGISTRATION
const ADD_PLOT = "ADD_PLOT";
const EDIT_PLOT = "EDIT_PLOT";
const GET_ALL_PLOT = "GET_ALL_PLOT";
const ADD_FARMER = "ADD_FARMER";
const FARMER_LOOKUP_INFO = " FARMER_LOOKUP_INFO";
const GET_FARMERS_LIST = " GET_FARMERS_LIST";
const UPDATE_PLOT = "UPDATE_PLOT";
const REMOVE_PLOT = "REMOVE_PLOT";
const REMOVE_ALL_PLOT = "REMOVE_ALL_PLOT";
const GET_ZONES_LIST = "GET_ZONES_LIST";

// COLLECTION CENTER

const ADD_COLLECTION_CENTER = "ADD_COLLECTION_CENTER";
const EDIT_COLLECTION_CENTER = "EDIT_COLLECTION_CENTER";
const GET_COLLECTION_CENTERS = "GET_COLLECTION_CENTERS";

// COMMON
const SET_LANGUAGE = "SET_LANGUAGE";
const SET_IS_CONNECTED = "SET_IS_CONNECTED";
const SET_USER_INFO_LOCAL = "SET_USER_INFO_LOCAL";

export {
  ADD_COLLECTION_CENTER,
  EDIT_COLLECTION_CENTER,
  GET_COLLECTION_CENTERS,
  ADD_TODO,
  GET_ZONES_LIST,
  SET_IS_CONNECTED,
  FARMER_LOOKUP_INFO,
  REMOVE_ALL_PLOT,
  SET_USER_REGIONS_LIST,
  REMOVE_TODO,
  UPDATE_TODO,
  GET_ALL_PLOT,
  CLEAR_ALL_TODOS,
  SET_USER_REGION,
  SET_USER_DATA,
  CLEAR_USER_DATA,
  SET_USER_INFO_LOCAL,
  SET_LANGUAGE,
  ADD_PLOT,
  UPDATE_PLOT,
  REMOVE_PLOT,
  EDIT_PLOT,
  ADD_FARMER,
  GET_FARMERS_LIST,
};
