const ADD_TODO = 'ADD_TODO';
const REMOVE_TODO = 'REMOVE_TODO';
const UPDATE_TODO = 'UPDATE_TODO';
const CLEAR_ALL_TODOS = 'CLEAR_ALL_TODOS';

const SET_USER_DATA = 'SET_USER_DATA';
const CLEAR_USER_DATA = 'CLEAR_USER_DATA';

export {
	ADD_TODO,
	REMOVE_TODO,
	UPDATE_TODO,
	CLEAR_ALL_TODOS,
	SET_USER_DATA,
	CLEAR_USER_DATA
};
