require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

# platform :ios, '12.4'
platform :ios, '15'

install! 'cocoapods', :deterministic_uuids => false

# rn_maps_path = '../node_modules/react-native-maps'
# pod 'react-native-google-maps', :path => rn_maps_path
# pod 'GoogleMaps', '3.5.0'
# pod 'Google-Maps-iOS-Utils'

 rn_maps_path = '../node_modules/react-native-maps'
    # pod 'react-native-google-maps', :path => rn_maps_path
    # pod 'GoogleMaps', '5.1.0' # <<<<---- I added the '5.1.0' version here
    # pod 'Google-Maps-iOS-Utils', '3.10.3' # <<<<---- I added the '3.10.3' version here


production = ENV["PRODUCTION"] == "1"

target 'maxtraceMobile' do
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # :hermes_enabled => flags[:hermes_enabled],
    :hermes_enabled => false,
    # to enable hermes on iOS, change `false` to `true` and then install pods

    #  commented 
    :production => production,
    :fabric_enabled => flags[:fabric_enabled],
    :flipper_configuration => FlipperConfiguration.enabled,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'maxtraceMobileTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    react_native_post_install(installer)
    # __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
